-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.comentario
(
    id_comentario serial NOT NULL,
    codigousuario smallint,
    codigopost smallint,
    contenido_comentario character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT comentario_pkey PRIMARY KEY (id_comentario)
);

CREATE TABLE IF NOT EXISTS public.post
(
    id_post serial NOT NULL,
    codigousuario smallint,
    titulo character varying(30) COLLATE pg_catalog."default",
    contenido_post character varying(400) COLLATE pg_catalog."default",
    fecha_publicacion date,
    CONSTRAINT post_pkey PRIMARY KEY (id_post)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    nombre character varying(15) COLLATE pg_catalog."default",
    pass character varying(40) COLLATE pg_catalog."default",
    descripcion character varying(90) COLLATE pg_catalog."default",
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.comentario
    ADD CONSTRAINT comentario_codigopost_fkey FOREIGN KEY (codigopost)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comentario
    ADD CONSTRAINT comentario_codigousuario_fkey FOREIGN KEY (codigousuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post
    ADD CONSTRAINT post_codigousuario_fkey FOREIGN KEY (codigousuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;